/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Event {
  export type DataStruct = {
    price: PromiseOrValue<BigNumberish>;
    time_start: PromiseOrValue<BigNumberish>;
    time_end: PromiseOrValue<BigNumberish>;
    event_name: PromiseOrValue<string>;
    event_symbol: PromiseOrValue<string>;
    company_name: PromiseOrValue<string>;
    eventLocation: PromiseOrValue<string>;
    event_address: PromiseOrValue<string>;
    owner: PromiseOrValue<string>;
    isOfflineEvent: PromiseOrValue<boolean>;
  };

  export type DataStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    string,
    boolean
  ] & {
    price: BigNumber;
    time_start: BigNumber;
    time_end: BigNumber;
    event_name: string;
    event_symbol: string;
    company_name: string;
    eventLocation: string;
    event_address: string;
    owner: string;
    isOfflineEvent: boolean;
  };
}

export interface EventFactoryInterface extends utils.Interface {
  functions: {
    "deployEvent(uint256,uint256,uint256,string,string,string,string,bool,string)": FunctionFragment;
    "getEventsByAddress(address)": FunctionFragment;
    "getTicketsByAddress(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deployEvent"
      | "getEventsByAddress"
      | "getTicketsByAddress"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployEvent",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventsByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketsByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventsByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketsByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface EventFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EventFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployEvent(
      _price: PromiseOrValue<BigNumberish>,
      _time_start: PromiseOrValue<BigNumberish>,
      _time_end: PromiseOrValue<BigNumberish>,
      _event_name: PromiseOrValue<string>,
      _event_symbol: PromiseOrValue<string>,
      _company_name: PromiseOrValue<string>,
      _event_location: PromiseOrValue<string>,
      _is_offline_event: PromiseOrValue<boolean>,
      base_uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getEventsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [Event.DataStructOutput[]] & { result: Event.DataStructOutput[] }
    >;

    getTicketsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[Event.DataStructOutput[]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deployEvent(
    _price: PromiseOrValue<BigNumberish>,
    _time_start: PromiseOrValue<BigNumberish>,
    _time_end: PromiseOrValue<BigNumberish>,
    _event_name: PromiseOrValue<string>,
    _event_symbol: PromiseOrValue<string>,
    _company_name: PromiseOrValue<string>,
    _event_location: PromiseOrValue<string>,
    _is_offline_event: PromiseOrValue<boolean>,
    base_uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getEventsByAddress(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<Event.DataStructOutput[]>;

  getTicketsByAddress(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<Event.DataStructOutput[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployEvent(
      _price: PromiseOrValue<BigNumberish>,
      _time_start: PromiseOrValue<BigNumberish>,
      _time_end: PromiseOrValue<BigNumberish>,
      _event_name: PromiseOrValue<string>,
      _event_symbol: PromiseOrValue<string>,
      _company_name: PromiseOrValue<string>,
      _event_location: PromiseOrValue<string>,
      _is_offline_event: PromiseOrValue<boolean>,
      base_uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getEventsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<Event.DataStructOutput[]>;

    getTicketsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<Event.DataStructOutput[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    deployEvent(
      _price: PromiseOrValue<BigNumberish>,
      _time_start: PromiseOrValue<BigNumberish>,
      _time_end: PromiseOrValue<BigNumberish>,
      _event_name: PromiseOrValue<string>,
      _event_symbol: PromiseOrValue<string>,
      _company_name: PromiseOrValue<string>,
      _event_location: PromiseOrValue<string>,
      _is_offline_event: PromiseOrValue<boolean>,
      base_uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getEventsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicketsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployEvent(
      _price: PromiseOrValue<BigNumberish>,
      _time_start: PromiseOrValue<BigNumberish>,
      _time_end: PromiseOrValue<BigNumberish>,
      _event_name: PromiseOrValue<string>,
      _event_symbol: PromiseOrValue<string>,
      _company_name: PromiseOrValue<string>,
      _event_location: PromiseOrValue<string>,
      _is_offline_event: PromiseOrValue<boolean>,
      base_uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getEventsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicketsByAddress(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
